CC ?= gcc
AR ?= ar
CFLAGS += -Wall

.PHONY : all
ifeq (darwin,$(findstring darwin,$(TARGET)))

all: $(OUT_DIR)/libmsgsend.a

$(OUT_DIR)/libmsgsend.a: $(OUT_DIR)/msgsend.o
	$(AR) rcs $(OUT_DIR)/libmsgsend.a $(OUT_DIR)/msgsend.o

$(OUT_DIR)/msgsend.o: src/msgsend.m
	$(CC) $(CFLAGS) $< -o $@ -c

else

all:

endif
