[package]
name = "core-graphics"
description = "Bindings to Core Graphics for macOS"
homepage = "https://github.com/servo/core-foundation-rs"
repository = "https://github.com/servo/core-foundation-rs"
version = "0.22.3"
authors = ["The Servo Project Developers"]
license = "MIT / Apache-2.0"

[features]
default = ["libc"]
elcapitan = ["libc"]
highsierra = []
libc = ["libc_", "core-foundation/libc"]

[dependencies]
bitflags = "1.0"
core-foundation = { path = "../core-foundation", version = "0.9", default-features = false }
core-graphics-types = { path = "../core-graphics-types", version = "0.1" }
foreign-types = "0.3.0"
# TODO: Use dep:libc functionality once in MSRV
libc_ = { version = "0.2", optional = true, package = "libc" }

[package.metadata.docs.rs]
default-target = "x86_64-apple-darwin"
