[package]
name = "core-graphics"
description = "Bindings to Core Graphics for OS X"
homepage = "https://github.com/servo/core-graphics-rs"
repository = "https://github.com/servo/core-foundation-rs"
version = "0.17.0"
authors = ["The Servo Project Developers"]
license = "MIT / Apache-2.0"

[features]
default = []
elcapitan = []
highsierra = []

[dependencies]
bitflags = "1.0"
core-foundation = { path = "../core-foundation", version = "0.6" }
foreign-types = "0.3.0"
libc = "0.2"
